### ISSUE TITLE
Possible missing words

### ISSUE THREAD

**Issue by RishabhMaheshwary** [simonepri/lm-scorer#2]
Is it possible to get top most probable missing words from a sentence using GPT-2? 
For example, we have a sentence "The doctor ran to the emergency room to see [MASK] patient." and we want to get the most probable words which could be at [MASK].

Thanks.

**Comment by simonepri** [comment]
You probably may want to use a masked language model for that (thought is tricky because .
See the following links:
https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.md#filling-masks
https://huggingface.co/transformers/quickstart.html#bert-example

With GPT-2 you can only feed `The doctor ran to the emergency room to see` and then predict the next word.

![image](https://user-images.githubusercontent.com/3505087/79242122-d21df300-7e6b-11ea-84d2-48faa95779fa.png)
Image from https://transformer.huggingface.co/doc/gpt2-large
